export const siteConfig = {
  baseUrl: 'https://kinda.info',
  siteUrl: 'https://kinda.info',
  title: '七月 / Kinda — 笔记、影像与作品',
  shortTitle: 'Kinda',
  author: '七月',
  authorAlternateNames: ['July', 'Kinda'],
  siteName: 'Kinda',
  timeZone: 'Asia/Shanghai',
  description: '七月的个人档案：写代码，拍照片，也记录那些值得慢慢想清楚的事。',
  language: 'zh-CN',
  keywords: ['Kinda', '七月', '个人网站', '笔记', '摄影', '独立开发', 'MDX'],
  email: '1142704468@qq.com',
  github: 'Alndaly',
  bilibili: 'https://space.bilibili.com/391938956',
  xiaohongshu: 'https://xhslink.cn/m/2gpKCIOPcgc',
  wechatQr: '/images/wechat-official-qr.jpg',
  siteRepo: 'kinda.info',
} as const;
