export const siteConfig = {
  baseUrl: 'https://kinda.info',
  siteUrl: 'https://kinda.info',
  title: 'Kinda — Notes, Frames & Things',
  shortTitle: 'Kinda',
  author: 'Kinda Hall',
  siteName: 'Kinda',
  timeZone: 'Asia/Shanghai',
  description: '关于代码、影像与日常感受的个人档案。把认真做过的东西，安静地留在这里。',
  language: 'zh-CN',
  keywords: ['Kinda', '个人网站', '笔记', '摄影', '独立开发', 'MDX'],
  email: '1142704468@qq.com',
  github: 'Alndaly',
  siteRepo: 'kinda.info',
} as const;
